// frontend/src/App.svelte
<script>
  import "bootstrap/dist/css/bootstrap.min.css";
  import "bootstrap/dist/js/bootstrap.bundle";
  import "svelte-material-ui/bare.css"
  import "./index.css"

  import { Router, Route } from "svelte-navigator";

  // Screens
  import Home from "./screens/Home.svelte";
  import Dashboard from "./screens/Dashboard.svelte";
</script>

<Router>
  <main class="wrapper">
    <Route path="/" component={Home} />
  <Route path="/dashboard" component={Dashboard} />
  </main>
</Router>

<style>
  .wrapper {
    height: 100%;
    min-height: 100vh;
    background-image: url("/src/assets/fondo.jpg");
    background-position: center;
    background-size: cover;
  }
</style>

// client/src/App.jsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { ThemeProvider, createTheme } from "@mui/material/styles";

import Background from "./assets/fondo.jpg"

// Screens
import AuthScreen from "./screens/auth";
import DashboardScreen from "./screens/dashboard";
import { Box, CssBaseline } from "@mui/material";

export default function App() {
  const theme = createTheme();

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Box
        width="100%"
        height="100%"
        minHeight="100vh"
        sx={{
          backgroundImage: `url(${Background})`,
          backgroundPosition: "center",
          backgroundSize: "cover"
        }}
      >
        <BrowserRouter>
          <Routes>
            <Route path="/" element={<AuthScreen />} />
            <Route path="/dashboard" element={<DashboardScreen />} />
          </Routes>
        </BrowserRouter>
      </Box>
    </ThemeProvider>
  );
}
