// frontend/src/screens/Dashboard.svelte
<script>
  import Sidebar from "../components/Sidebar.svelte";
  import Usuarios from "../components/usuarios/Usuarios.svelte";
  import Reactivos from "../components/reactivos/Reactivos.svelte";
  import Equipos from "../components/equipos/Equipos.svelte";

  let section = "usuarios";

  function handleSection(newSection) {
    section = newSection;
  }
</script>

<div class="d-flex">
  <div class="columns col-md-3 overflow-auto">
    <Sidebar {section} {handleSection} />
  </div>
  <div class="columns dashboard col-md-9 overflow-auto p-4">
    {#if section === "usuarios"}
      <Usuarios />
    {/if}
    {#if section === "reactivos"}
      <Reactivos />
    {/if}
    {#if section === "equipos"}
      <Equipos />
    {/if}
  </div>
</div>

<style>
  .columns {
    max-height: 100vh;
  }

  .dashboard {
    margin-top: 1rem;
  }
</style>

// frontend/src/pages/Dashboard.tsx
import { useState } from "react";
import { Box, Grid, GridItem } from "@chakra-ui/react";
import Layout from "../components/Layout";
import Sidebar from "../components/Sidebar";

import Usuarios from "../components/Dashboard/Usuarios";
import Equipos from "../components/Dashboard/Equipos";
import Reactivos from "../components/Dashboard/Reactivos";

export default function Dashboard() {
  const [section, setSection] = useState("usuarios");

  return (
    <Layout>
      <Box style={{ height: "94vh", maxHeight: "94vh" }}>
        <Grid
          h="100%"
          templateRows="repeat(2, 1fr)"
          templateColumns="repeat(12, 1fr)"
          gap={4}
        >
          <GridItem rowSpan={2} colSpan={2}>
            <Sidebar section={section} setSection={setSection} />
          </GridItem>
          <GridItem rowSpan={2} colSpan={10} overflowY="auto">
            {section === "usuarios" && <Usuarios />}
            {section === "equipos" && <Equipos />}
            {section === "reactivos" && <Reactivos />}
          </GridItem>
        </Grid>
      </Box>
    </Layout>
  );
}
